# pyrefly: ignore [missing-import]
import cv2
# pyrefly: ignore [missing-import]
from ultralytics import YOLO
import time
import requests
import os
import sys
from dotenv import load_dotenv

# Add src/ to path for shared modules
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from supabase_client import supabase
from dashboard_api.models.complaint import ComplaintPayload, ComplaintRecord

load_dotenv(os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), ".env"))

# ---------------- CONFIG ----------------
MODEL_PATH = os.getenv("MODEL_PATH")
CONF_THRESHOLD = float(os.getenv("CONF_THRESHOLD", 0.3))
print(f"[CONFIG] CONF_THRESHOLD = {CONF_THRESHOLD}")
MIN_BOX_AREA = int(os.getenv("MIN_BOX_AREA", 500))
N8N_WEBHOOK_URL = os.getenv("N8N_WEBHOOK_URL")
LOCATION = os.getenv("LOCATION", "Unknown Location")

# Project root (one level up from src/)
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# ---------- TIME-BASED ACCUMULATION VARIABLES ----------

GARBAGE_PERCENT_THRESHOLD = 20.0   # % threshold for garbage
PERSISTENCE_TIME = 300             # seconds (300 seconds / 5 minutes for testing)
first_detected_time = None         # stores first detection time
complaint_triggered = False        # prevents repeated triggers
threshold_buffer = 5.0             # buffer to avoid rapid toggling

# ---------- LOCATION SYNC CONFIG ----------
last_location_check = 0.0
LOCATION_CHECK_INTERVAL = 30.0     # check backend location API every 30 seconds

# ---------------- LOAD MODEL ----------------
model = YOLO(MODEL_PATH)


# ---------------- OPEN WEBCAM ----------------
cap = cv2.VideoCapture(0)

if not cap.isOpened():
    print("Error: Could not open webcam")
    exit()

print("Webcam started. Press 'q' to quit.")


#---------------Complaint Format Function---------------
def garbage_complaint_format(location, timestamp, garbage_percentage, elapsed_time, image_path):
    complaint_text = f"""
        AUTOMATED GARBAGE COMPLAINT

        Location: {location}
        Timestamp: {timestamp}
        Detected Time: {elapsed_time:.2f} seconds
        Garbage Percentage: {garbage_percentage:.2f}%
        Evidence Image: {image_path}

        This is an automated complaint generated by the Garbage Detection System.
        """

    payload = {
        "location": location,
        "timestamp": timestamp,
        "garbage_percentage": float(round(garbage_percentage, 2)),
        "detected_time": float(round(elapsed_time, 2)),
        "image_path": image_path
    }

    return complaint_text, payload



#---------------Send to N8N Function---------------
def send_to_n8n(payload):
    if not N8N_WEBHOOK_URL:
        print("Webhook URL not configured.")
        return

    try:
        response = requests.post(N8N_WEBHOOK_URL, json=payload, timeout=5)
        if response.status_code == 200:
            print("Complaint sent to n8n successfully.")
        else:
            print(f"Failed to send complaint. Status: {response.status_code}")
    except Exception as e:
        print(f"Error sending complaint: {e}")


#---------------Upload Evidence to Supabase Storage---------------
def upload_evidence_to_supabase(frame, filename: str) -> str:
    """Encode frame as JPEG in-memory and upload directly to Supabase Storage."""
    try:
        _, buffer = cv2.imencode(".jpg", frame)
        image_bytes = buffer.tobytes()

        supabase.storage.from_("evidence").upload(
            path=filename,
            file=image_bytes,
            file_options={"content-type": "image/jpeg"}
        )

        public_url = supabase.storage.from_("evidence").get_public_url(filename)
        print(f"☁️ Evidence uploaded to Supabase: {public_url}")
        return public_url
    except Exception as e:
        print(f"❌ Supabase upload error: {e}")
        return ""


#---------------Insert Complaint into Supabase DB---------------
def save_complaint_to_supabase(payload_dict: dict, evidence_url: str):
    """Validate payload and insert a complaint record into Supabase."""
    try:
        payload = ComplaintPayload(**payload_dict)
        record = ComplaintRecord.from_payload(payload, evidence_url=evidence_url)

        row = record.model_dump(exclude={"id", "timestamp"})

        result = supabase.table("complaints").insert(row).execute()
        print(f"✅ Complaint saved to Supabase DB: {result.data}")
    except Exception as e:
        print(f"❌ Supabase DB insert error: {e}")


# ---------------- MAIN LOOP ----------------
while True:
    current_time = time.time()
    # Periodically fetch active location from the dashboard API
    if current_time - last_location_check >= LOCATION_CHECK_INTERVAL:
        last_location_check = current_time
        try:
            response = requests.get("http://127.0.0.1:8000/api/location", timeout=0.8)
            if response.status_code == 200:
                data = response.json()
                if data and "address" in data:
                    new_loc = data["address"]
                    if new_loc != LOCATION:
                        LOCATION = new_loc
                        print(f"[LOCATION UPDATE] Camera location updated dynamically to: {LOCATION}")
        except Exception:
            pass

    ret, frame = cap.read()
    if not ret:
        print("Error: Could not read frame")
        break

    h, w, _ = frame.shape
    frame_area = h * w
    garbage_area = 0

    # -------- YOLO INFERENCE --------
    results = model(frame, conf=CONF_THRESHOLD, verbose=False)[0]

    print("Detections found:", len(results.boxes))

    for box in results.boxes:
        # Always convert tensor to CPU numpy
        x1, y1, x2, y2 = box.xyxy[0].cpu().numpy().astype(int)
        box_area = (x2 - x1) * (y2 - y1)

        confidence = float(box.conf[0].cpu())
        print(f"Box area: {box_area}  conf: {confidence:.2f}")

        # DRAW BOX (ALWAYS)
        cv2.rectangle(frame, (x1, y1), (x2, y2), (0, 255, 0), 2)

        # COUNT AREA ONLY IF LARGE ENOUGH
        if box_area >= MIN_BOX_AREA:
            garbage_area += box_area

    # -------- GARBAGE PERCENTAGE --------
    garbage_percentage = (garbage_area / frame_area) * 100 if frame_area else 0
    garbage_percentage = min(garbage_percentage, 100.0)

    # -------- SEVERITY DETECTION --------
    current_time = time.time()

    if garbage_percentage >= (GARBAGE_PERCENT_THRESHOLD - threshold_buffer):
        print(f"[{current_time}] High Garbage level detected: {garbage_percentage:.2f}%")

        if first_detected_time is None:
            first_detected_time = current_time
            print(f"[{current_time}] First Garbage detection time recorded.")
        else:
            elapsed_time = current_time - first_detected_time
            print(f"Garbage present for {elapsed_time:.2f} seconds")

            if elapsed_time >= 300 and not complaint_triggered:
                print(f"[{current_time}] High Garbage level detected for over 5 minutes: {garbage_percentage:.2f}%")

    else:
        if first_detected_time is not None:
            print(f"[{current_time}] Garbage level dropped below threshold. Resetting timer.")
        first_detected_time = None
        complaint_triggered = False

    # -------- DISPLAY TEXT --------
    cv2.putText(
        frame,
        f"Garbage: {garbage_percentage:.2f}%",
        (20, 40),
        cv2.FONT_HERSHEY_COMPLEX,
        0.7,
        (0, 0, 255),
        2
    )
    print("-----------------------------------------------------------------------")

    #-------------Detected Time Print--------------
    if first_detected_time is not None:
        elapsed_time = current_time - first_detected_time
        cv2.putText(
            frame,
            f"Detected Time: {int(elapsed_time)}s",
            (20, 70),
            cv2.FONT_HERSHEY_COMPLEX,
            0.7,
            (255, 0, 0),
            2
        )
    else:
        cv2.putText(
            frame,
            "Detected Time: 0s",
            (20, 70),
            cv2.FONT_HERSHEY_COMPLEX,
            0.7,
            (255, 0, 0),
            2
        )

    #----------------Evidence Capture----------------
    if (garbage_percentage >= GARBAGE_PERCENT_THRESHOLD and first_detected_time is not None and (current_time - first_detected_time) >= PERSISTENCE_TIME and not complaint_triggered):
        timestamp = time.strftime("%Y%m%d-%H%M%S")
        filename = f"garbage_{timestamp}.jpg"

        elapsed_time = current_time - first_detected_time
        print(f"[{timestamp}] 📸 Evidence captured (uploading to cloud...)")

        complaint_text, payload = garbage_complaint_format(  
            location=LOCATION,
            timestamp=timestamp,
            garbage_percentage=garbage_percentage,
            elapsed_time=elapsed_time,
            image_path=filename
        )
        print("----- Generated Complaint -----")
        print(complaint_text)

        send_to_n8n(payload)

        # -------- SUPABASE: Upload evidence + save complaint --------
        evidence_url = upload_evidence_to_supabase(frame, filename)
        save_complaint_to_supabase(payload, evidence_url)

        # -------- SSE: Notify dashboard for real-time update --------
        try:
            from dashboard_api.models.complaint import classify_severity
            notify_data = {
                "timestamp": timestamp,
                "location": LOCATION,
                "severity": classify_severity(garbage_percentage),
                "garbage_pct": round(garbage_percentage, 2),
                "duration_seconds": int(elapsed_time),
                "evidence_url": evidence_url,
            }
            requests.post("http://127.0.0.1:8000/notify", json=notify_data, timeout=2)
            print("📡 Dashboard notified via SSE.")
        except Exception as e:
            print(f"⚠️ Dashboard SSE notify skipped (dashboard may be offline): {e}")

        complaint_triggered = True


    # -------- SHOW FRAME AFTER DRAWING --------
    cv2.imshow("Garbage Detection", frame)

    # -------- EXIT --------
    key = cv2.waitKey(1) & 0xFF

    if key == ord('q'):
        break

    if key == ord('c'):
        print("⚠️ FORCE COMPLAINT TRIGGER")
        first_detected_time = time.time() - (PERSISTENCE_TIME + 1)
        complaint_triggered = False



# ---------------- CLEANUP ----------------
cap.release()
cv2.destroyAllWindows()



