import cv2
from ultralytics import YOLO
import time
import requests


# ---------------- CONFIG ----------------
MODEL_PATH = "C:\\Users\\Lakshay\\Desktop\\Portfolio\\CleanCam AI\\model\\train5\\weights\\best.pt"
CONF_THRESHOLD = 0.3
MIN_BOX_AREA = 500
n8n_webhook_url = "https://tabernacular-korbin-indigenously.ngrok-free.dev/webhook/12962283-57d4-413c-8a93-f6ccda6e98e7"  


# ---------- TIME-BASED ACCUMULATION VARIABLES ----------

GARBAGE_PERCENT_THRESHOLD = 20.0   # % threshold for garbage
PERSISTENCE_TIME = 10              # seconds (10 seconds for testing)
first_detected_time = None         # stores first detection time
complaint_triggered = False        # prevents repeated triggers
threshold_buffer = 5.0             # buffer to avoid rapid toggling

# ---------------- LOAD MODEL ----------------
model = YOLO(MODEL_PATH)

# ---------------- OPEN WEBCAM ----------------
cap = cv2.VideoCapture(0)

if not cap.isOpened():
    print("Error: Could not open webcam")
    exit()

print("Webcam started. Press 'q' to quit.")


#---------------Complaint Format Function---------------
def garbage_complaint_format(location, timestamp, garbage_percentage, elapsed_time, image_path):
    complaint_text = f"""
        AUTOMATED GARBAGE COMPLAINT

        Location: {location}
        Timestamp: {timestamp}
        Detected Time: {elapsed_time:.2f} seconds
        Garbage Percentage: {garbage_percentage:.2f}%
        Evidence Image: {image_path}

        This is an automated complaint generated by the Garbage Detection System.
        """

    payload = {
        "location": location,
        "timestamp": timestamp,
        "garbage_percentage": float(round(garbage_percentage, 2)),
        "detected_time": float(round(elapsed_time, 2)),
        "image_path": image_path
    }

    return complaint_text, payload



#---------------Send to N8N Function---------------
def send_to_n8n(payload):
    try:
        response = requests.post(n8n_webhook_url, json=payload)
        if response.status_code == 200:
            print("Complaint sent to n8n successfully.")
        else:
            print(f"Failed to send complaint to n8n. Status code: {response.status_code}")
    except Exception as e:
        print(f"Error sending complaint to n8n: {e}")


# ---------------- MAIN LOOP ----------------
while True:
    ret, frame = cap.read()
    if not ret:
        print("Error: Could not read frame")
        break

    h, w, _ = frame.shape
    frame_area = h * w
    garbage_area = 0

    # -------- YOLO INFERENCE --------
    results = model(frame, conf=CONF_THRESHOLD, verbose=False)[0]

    print("Detections found:", len(results.boxes))

    for box in results.boxes:
        # Always convert tensor to CPU numpy
        x1, y1, x2, y2 = box.xyxy[0].cpu().numpy().astype(int)
        box_area = (x2 - x1) * (y2 - y1)

        print("Box area:", box_area)

        # DRAW BOX (ALWAYS)
        cv2.rectangle(frame, (x1, y1), (x2, y2), (0, 255, 0), 2)

        # COUNT AREA ONLY IF LARGE ENOUGH
        if box_area >= MIN_BOX_AREA:
            garbage_area += box_area

    # -------- GARBAGE PERCENTAGE --------
    garbage_percentage = (garbage_area / frame_area) * 100 if frame_area else 0
    garbage_percentage = min(garbage_percentage, 100.0)

    # -------- SEVERITY DETECTION --------
    current_time = time.time()

    if garbage_percentage >= (GARBAGE_PERCENT_THRESHOLD - threshold_buffer):
        print(f"[{current_time}] High Garbage level detected: {garbage_percentage:.2f}%")

        if first_detected_time is None:
            first_detected_time = current_time
            print(f"[{current_time}] First Garbage detection time recorded.")
        else:
            elapsed_time = current_time - first_detected_time
            print(f"Garbage present for {elapsed_time:.2f} seconds")

            if elapsed_time >= 300 and not complaint_triggered:
                print(f"[{current_time}] High Garbage level detected for over 5 minutes: {garbage_percentage:.2f}%")

    else:
        if first_detected_time is not None:
            print(f"[{current_time}] Garbage level dropped below threshold. Resetting timer.")
        first_detected_time = None
        complaint_triggered = False

    # -------- DISPLAY TEXT --------
    cv2.putText(
        frame,
        f"Garbage: {garbage_percentage:.2f}%",
        (20, 40),
        cv2.FONT_HERSHEY_COMPLEX,
        0.7,
        (0, 0, 255),
        2
    )
    print("-----------------------------------------------------------------------")

    #-------------Detected Time Print--------------
    if first_detected_time is not None:
        elapsed_time = current_time - first_detected_time
        cv2.putText(
            frame,
            f"Detected Time: {int(elapsed_time)}s",
            (20, 70),
            cv2.FONT_HERSHEY_COMPLEX,
            0.7,
            (255, 0, 0),
            2
        )
    else:
        cv2.putText(
            frame,
            "Detected Time: 0s",
            (20, 70),
            cv2.FONT_HERSHEY_COMPLEX,
            0.7,
            (255, 0, 0),
            2
        )

    #----------------Evidence Capture----------------
    if (garbage_percentage >= GARBAGE_PERCENT_THRESHOLD and first_detected_time is not None and (current_time - first_detected_time) >= PERSISTENCE_TIME and not complaint_triggered):
        timestamp = time.strftime("%Y%m%d-%H%M%S")
        filename = f"evidence/garbage_{timestamp}.jpg"

        cv2.imwrite(filename, frame)

        elapsed_time = current_time - first_detected_time
        print(f"[{timestamp}] 📸 Evidence saved: {filename}")

        complaint_text = garbage_complaint_format(  
            location="123 Main St, Anytown",
            timestamp=timestamp,
            garbage_percentage=garbage_percentage,
            elapsed_time=elapsed_time,
            image_path=filename
        )
        print("----- Generated Complaint -----")
        print(complaint_text)

        complaint_triggered = True


    # -------- SHOW FRAME AFTER DRAWING --------
    cv2.imshow("Garbage Detection", frame)

    # -------- EXIT --------
    key = cv2.waitKey(1) & 0xFF

    if key == ord('q'):
        break

    if key == ord('c'):
        print("⚠️ FORCE COMPLAINT TRIGGER")
        first_detected_time = time.time() - (PERSISTENCE_TIME + 1)
        complaint_triggered = False


# ---------- TEST N8N WEBHOOK ----------
send_to_n8n({
    "location": "TEST",
    "timestamp": "NOW",
    "garbage_percentage": 99,
    "detected_time": 5,
    "image_path": "test.jpg"
})



# ---------------- CLEANUP ----------------
cap.release()
cv2.destroyAllWindows()



